#!/bin/bash
set -x
program=webad
iptables -D INPUT -p tcp --sport 80 -j QUEUE
iptables -D OUTPUT -p tcp --dport 80 -j QUEUE
iptables -A INPUT -p tcp --sport 80 -j QUEUE
iptables -A OUTPUT -p tcp --dport 80 -j QUEUE
while true
do
	num=`ps -ef|grep $program|grep -v grep|wc -l`
	if [ $num -eq 0 ];then
		$program &
	fi
sleep 10
done
